name: lasif
channels:
    - conda-forge
    - defaults
    - jmcmurray
dependencies:
    - python=3.7
    - numpy=1.16
    - scipy
    - pyproj=1.9
    - obspy
    - cartopy
    - pyasdf
    - progressbar
    - colorama
    - joblib
    - pytest
    - nose
    - mock
    - pyqt
    - pip
    - sphinx
    - sphinx_rtd_theme
    - seaborn
    - numexpr
    - ipython
    - dill
    - prov
    - pandas
    - h5py
    - pyqtgraph
    - ipykernel
    - pathlib
    - jupyter
    - jupyter_contrib_nbextensions
    - jupytext
    - ipywidgets
    - pythreejs
    - json
    - pip:
        - geographiclib
        - flask-cache
        - geojson
        - flake8
        - toml
        - tqdm
        - cmasher
